apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev
commonLabels:
  env: dev
namespace: demo

resources:
  - ../../base

configMapGenerator:
  - name: demo-config
    behavior: replace
    literals:
      - SERVER_PORT=8080
      # add env-specific config here

patches:
  - path: patch-deployment.yaml

images:
  - name: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/REPO_NAME
    newName: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/REPO_NAME
    newTag: main   # CI overrides with sha
