apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -dev
commonLabels: { env: dev }
namespace: demo

resources:
  - ../../base/demo-app
 



configMapGenerator:
  - literals: 
      - SERVER_PORT=8080
    name: demo-config  

secretGenerator:
  - name: demo-secrets
    envs:
      - secrets.env    

images:
  - name: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/REPO_NAME
    newName: ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/REPO_NAME
    newTag: main
