apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 65.0.0
    releaseName: monitor
    namespace: monitoring
    includeCRDs: false   # skip emitting CRDs; they must already exist
    valuesInline:
      grafana:
        enabled: true
        service:
          type: ClusterIP         # use port-forward instead of a LoadBalancer
        testFramework:
          enabled: false          # stop the failing test pod
      prometheus:
        prometheusSpec:
          retention: 6h
          scrapeInterval: 15s
          # ensure Prometheus discovers ServiceMonitors/PodMonitors cluster-wide
          serviceMonitorSelector: {}
          serviceMonitorNamespaceSelector: {}
          podMonitorSelector: {}
          podMonitorNamespaceSelector: {}
          probeSelector: {}
          probeNamespaceSelector: {}
      alertmanager:
        alertmanagerSpec:
          replicas: 1             # emptyDir storage (no PVC) by default
