name:  build 

on:
  workflow_call:
    outputs:
      image_tag:
        description: "Immutable image tag (sha-<short>)"
        value: ${{ jobs.build.outputs.image_tag }}
      repository_uri:
        description: "ECR repository URI"
        value: ${{ jobs.build.outputs.repository_uri }}

permissions:
  id-token: write   # for AWS OIDC
  contents: read

env:
  AWS_REGION: eu-north-1
  ACCOUNT_ID: "275581418810"
  REPO_NAME: DevOps-assignment
  EKS_CLUSTER_NAME: demo-eks
  K8S_NAMESPACE: app
  IMAGE_TAG: sha-${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::275581418810:role/springboot-k8s-github-deployer
          role-session-name: gha-deploy

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # Optional: enable multi-arch emulation if PLATFORMS includes arm64
      - name: Set up QEMU
        if: contains(env.PLATFORMS || 'linux/amd64','arm64')
        uses: docker/setup-qemu-action@v3

      - name: Bake & push (multi-arch ready)
        run: |
          export ACCOUNT_ID=${{ env.ACCOUNT_ID }}
          export AWS_REGION=${{ env.AWS_REGION }}
          export REPO_NAME=${{ env.REPO_NAME }}
          export TAG=${{ env.IMAGE_TAG }}
          # Optionally: export PLATFORMS="linux/amd64,linux/arm64"
          docker buildx bake -f docker-bake.hcl release