name: Secret Scan

on:
  pull_request:
    branches:
      - develop

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.3.0

      - name: Run Gitleaks
        run: |
          docker run --rm -v "$(pwd):/path" ghcr.io/gitleaks/gitleaks:latest dir -l trace --redact -v /path