name: Terraform Apply

on:
  push:
    branches: 
      - main 
    paths:
      - 'ops/terraform/**'
      - '.github/workflows/terraform-apply.yaml'
  workflow_dispatch:
    inputs:
      var_file:
        description: 'Optional tfvars file relative to ops/terraform (e.g., env/prod.tfvars)'
        required: false
        type: string

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION:  ${{ vars.AWS_REGION }}
  TF_WORKDIR:  ops/terraform
  TF_VERSION:  1.9.5
  TF_VAR_github_org:  ${{ github.repository_owner }}
  TF_VAR_github_repo: ${{ github.event.repository.name }}
 

jobs:
  apply:
    runs-on: ubuntu-latest
    concurrency:
      group: terraform-apply
      cancel-in-progress: false

    defaults:
      run:
        working-directory: ${{ env.TF_WORKDIR }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: gha-terraform-${{ github.run_id }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate -no-color

 
      - name: Terraform apply (non-interactive)
        run: |
          if [ -n "${{ inputs.var_file }}" ]; then
            terraform apply -input=false -auto-approve -var-file="${{ inputs.var_file }}"
          else
            terraform apply -input=false -auto-approve
          fi
     
      - name: Output summary
        run: |
          echo "## Terraform Apply ✅" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Directory:** \`${{ env.TF_WORKDIR }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Region:** \`${{ env.AWS_REGION }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Var file:** \`${{ inputs.var_file || '(none)' }}\`" >> $GITHUB_STEP_SUMMARY
